dosfstools: add fsck.vfat symlink only in target version
* for native version it causes following QA issue:
  NOTE: recipe dosfstools-native-4.1-r0: task do_populate_sysroot: Started
  ERROR: dosfstools-native-4.1-r0 do_populate_sysroot: sstate found an absolute path symlink /OE/build/owpb/webos-ports/tmp-glibc/work/x86_64-linux/dosfstools-native/4.1-r0/sysroot-destdir/OE/build/owpb/webos-ports/tmp-glibc/work/x86_64-linux/dosfstools-native/4.1-r0/recipe-sysroot-native/sbin/fsck.vfat pointing at /OE/build/owpb/webos-ports/tmp-glibc/work/x86_64-linux/dosfstools-native/4.1-r0/recipe-sysroot-native/usr/sbin/fsck.vfat. Please replace this with a relative link.
  NOTE: recipe dosfstools-native-4.1-r0: task do_populate_sysroot: Succeeded

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>